/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorCard: typeof import('./src/components/author/AuthorCard.vue')['default']
    EvaluateDialog: typeof import('./src/components/EvaluateDialog/index.vue')['default']
    FilterHistory: typeof import('./src/components/FilterHistory/index.vue')['default']
    FilterPreset: typeof import('./src/components/FilterPreset/index.vue')['default']
    KolReviewsTab: typeof import('./src/components/KolReviewsTab/index.vue')['default']
    Permission: typeof import('./src/components/Permission/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlbotEmbedded: typeof import('./src/components/SqlbotEmbedded/index.vue')['default']
    TagFilter: typeof import('./src/components/TagFilter/index.vue')['default']
    TagSelector: typeof import('./src/components/TagSelector/index.vue')['default']
  }
}

// For TSX support
declare global {
  const AuthorCard: typeof import('./src/components/author/AuthorCard.vue')['default']
  const EvaluateDialog: typeof import('./src/components/EvaluateDialog/index.vue')['default']
  const FilterHistory: typeof import('./src/components/FilterHistory/index.vue')['default']
  const FilterPreset: typeof import('./src/components/FilterPreset/index.vue')['default']
  const KolReviewsTab: typeof import('./src/components/KolReviewsTab/index.vue')['default']
  const Permission: typeof import('./src/components/Permission/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SqlbotEmbedded: typeof import('./src/components/SqlbotEmbedded/index.vue')['default']
  const TagFilter: typeof import('./src/components/TagFilter/index.vue')['default']
  const TagSelector: typeof import('./src/components/TagSelector/index.vue')['default']
}